logging : 
      level : 
          io.swagger.models.parameters.AbstractSerializableParameter : error
        
spring:
    application :
           name: Diciccos
    main :
        banner-mode : off       
    output :
       enabled :  ALWAYS
    profiles :
           active : dev
    jackson : 
           serialization : 
                     fail-on-empty-beans : false