package com.prakat.middleware.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "delivery_addresses")
@ApiModel(description = "All details about the delivery address")
public class DeliveryAddress implements Serializable {

	private static final long serialVersionUID = 2405004484124984939L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "delivery_address_id")
	@ApiModelProperty(notes = "Id generated by server for Delivery Address record")
	private int deliveryAddressId;
	@Column(name = "address_type")
	@NotNull(message = "Address Type is mandatory")
	@ApiModelProperty(notes="Address Type")
	private String addressType;
	@Column(name = "user_id")
	@NotNull(message = "User id is mandatory")
	@ApiModelProperty(notes="User Id")
	private Integer userId;
	@Column(name = "address_line_1")
	@NotNull(message = "Address Line 1 is mandatory")
	@Size(max = 50 , message = "Address Line 1 should have maximum 50 characters")
	@ApiModelProperty(value ="Address Line 1", required = true)
	private String addressLine1;
	@Column(name = "address_line_2")
	@Size(max = 50 , message = "Address Line 2 should have maximum 50 characters")
	@ApiModelProperty(value ="Address Line 2")
	private String addressLine2;
	@Column(name = "city")
	@NotNull(message = "City Name is mandatory")
	@Size(max = 50 , message = "City Name should have maximum 50 characters")
	@ApiModelProperty(value ="City Name", required = true)
	private String city;
	@Column(name = "state")
	@NotNull(message = "State Name is mandatory")
	@Size(max = 50 , message = "State Name should have maximum 50 characters")
	@ApiModelProperty(value ="State Name", required = true)
	private String state;
	@Column(name = "zip_code")
	@NotNull(message = "Zip Code is mandatory")
	@Size(max = 50 , message = "Address Line 2 should have maximum 50 characters")
	@ApiModelProperty(value ="Zip Code", required = true)
	private String zipCode;
	@Column(name = "country")
	@NotNull(message = "Country Name is mandatory")
	@Size(max = 50 , message = "Address Line 2 should have maximum 50 characters")
	@ApiModelProperty(value ="Country Name", required = true)
	private String country;
	@Column(name = "phone_number")
	@NotNull(message = "Phone Number is mandatory")
	@Size(max = 50 , message = "Phone Number should have maximum 50 characters")
	@ApiModelProperty(value ="Phone Number", required = true)
	private String phoneNumber;
	@Column(name = "latitude")
	private Double latitude;
	@Column(name = "longitude")
	private Double longitude;
	@Column(name = "radius")
	private Integer radius;
	
	public int getDeliveryAddressId() {
		return deliveryAddressId;
	}
	public void setDeliveryAddressId(int deliveryAddressId) {
		this.deliveryAddressId = deliveryAddressId;
	}
	public String getAddressType() {
		return addressType;
	}
	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public String getAddressLine1() {
		return addressLine1;
	}
	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}
	public String getAddressLine2() {
		return addressLine2;
	}
	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getZipCode() {
		return zipCode;
	}
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public Double getLatitude() {
		return latitude;
	}
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}
	public Double getLongitude() {
		return longitude;
	}
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}
	public Integer getRadius() {
		return radius;
	}
	public void setRadius(Integer radius) {
		this.radius = radius;
	}
}
