package com.prakat.middleware.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "order_dish_details")
@ApiModel(description = "All details about the order dish")
public class DishDetails{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "dish_details_id")
	@ApiModelProperty(notes = "Id generated by server for DishDetails record , not required while creating new record")
	private int dishDetailsId;
	@Column(name="dish_name_id")
	@ApiModelProperty(notes="Id of DishName record")
	private int dishNameId;
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="order_id", referencedColumnName = "order_id", nullable = false)
    private Order order;
	@ElementCollection
	@ApiModelProperty(notes="List od DishExtra record Id")
	private List<Integer> dishExtraIdList;
	@Column(name="dish_quantity")
	@ApiModelProperty(notes="Number of Dishes")
	private int dishQuantity;
	@ApiModelProperty(notes="Total Amount per Dish")
	@Column(name="dish_total_amount")
	private double dishTotalAmount;
	public int getDishDetailsId() {
		return dishDetailsId;
	}
	public void setDishDetailsId(int dishDetailsId) {
		this.dishDetailsId = dishDetailsId;
	}
	public int getDishNameId() {
		return dishNameId;
	}
	public void setDishNameId(int dishNameId) {
		this.dishNameId = dishNameId;
	}
	public Order getOrder() {
		return order;
	}
	public void setOrder(Order order) {
		this.order = order;
	}
	public List<Integer> getDishExtraIdList() {
		return dishExtraIdList;
	}
	public void setDishExtraIdList(List<Integer> dishExtraIdList) {
		this.dishExtraIdList = dishExtraIdList;
	}
	public int getDishQuantity() {
		return dishQuantity;
	}
	public void setDishQuantity(int dishQuantity) {
		this.dishQuantity = dishQuantity;
	}
	public double getDishTotalAmount() {
		return dishTotalAmount;
	}
	public void setDishTotalAmount(double dishTotalAmount) {
		this.dishTotalAmount = dishTotalAmount;
	}
}
